<?php

namespace ErmineApp\JabberBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfmessagearchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfmessagearchiveRepository extends EntityRepository
{
}
