services:
    admin.twig_extension:
        class: ErmineApp\AdminBundle\Twig\AdminExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            - @app_user_repository
            - @app_user_manager_service


#    sonata.admin.managers:
#        class: ErmineApp\UserBundle\Admin\AdministratorsAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Administrators" }
#        arguments: [~, ErmineApp\UserBundle\Entity\User, SonataAdminBundle:CRUD]
#
#        calls:
#            - [ setTranslationDomain, [ErmineAppUserBundle]]

    sonata.admin.chatbourd.users:
        class: ErmineApp\JabberBundle\Admin\ChatUserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Users" }
        arguments: [~, ErmineApp\JabberBundle\Entity\AuthData, SonataAdminBundle:CRUD]

        calls:
            - [ setTranslationDomain, [ErmineAppJabberBundle]]

    sonata.admin.chatbourd.chats:
        class: ErmineApp\JabberBundle\Admin\ChatAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Chats", label: "Chats" }
        arguments: [~, ErmineApp\JabberBundle\Entity\Chat, SonataAdminBundle:CRUD]

        calls:
            - [ setTranslationDomain, [ErmineAppJabberBundle]]

    sonata.admin.chatbourd.messages:
        class: ErmineApp\JabberBundle\Admin\OfmessagearchiveAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Chats", label: "Messages" }
        arguments: [~, ErmineApp\JabberBundle\Entity\Ofmessagearchive, SonataAdminBundle:CRUD]

        calls:
            - [ setTranslationDomain, [ErmineAppJabberBundle]]
