<?php

namespace ErmineApp\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
    /**
     * @param Session $session
     */
    public function save(Session $session)
    {
        $this->getEntityManager()->persist($session);
        $this->getEntityManager()->flush();
    }

    /**
     * @param Session $entity
     */
    public function remove(Session $entity){
        $em = $this->getEntityManager();
        $em->remove($entity);
        $em->flush();
    }
}
