Rest_User :
    type : rest
    resource: "@ErmineAppUserBundle/Resources/config/routing_rest.yml"

#Rest_Intersts :
#    type : rest
#    resource: "@ErmineAppInterestsBundle/Resources/config/routing_rest.yml"