ermine_app_response:
    resource: "@ErmineAppResponseBundle/Resources/config/routing.yml"
    prefix:   /

ermine_app_social_nets:
    resource: "@ErmineAppSocialNetsBundle/Resources/config/routing.yml"
    prefix:   /

ermine_app_files:
    resource: "@ErmineAppFilesBundle/Resources/config/routing.yml"
    prefix:   /

ermine_app_admin:
    resource: "@ErmineAppAdminBundle/Resources/config/routing.yml"
    prefix:   /

ermine_app_user:
    resource: "@ErmineAppUserBundle/Resources/config/routing.yml"
    prefix:   /




app:
    resource: "@AppBundle/Controller/"
    type:     annotation



#REST
rest :
    type : rest
    resource : "routing_rest.yml"
    prefix : /api



logout:
    path:   /logout

account_register:
    path:     /register
    defaults: { _controller: ErmineAppUserBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: ErmineAppUserBundle:Account:create }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin